### ISSUE TITLE
./config.json error

### ISSUE THREAD

**Issue by hfahrudin** [Credwa/node-mongo-test-api#1]
nice app! i try to clone your repo so i can learn about it. but i faced this isues when starting this app. it says `Error: Cannot find module './config.json'` . it will be wonderfull if you can help me. cheers!

**Comment by Credwa** [comment]
Hey thanks.
It's just a JSON file which contains config variables I can't really put on github for security reasons (even though its just a test app) but it looks like this:

`{
  "development": {
    "JWT_SECRET": "randomSecretHere",
    "MONGODB_URI": "mongodb://devDatabaseURLHere"
  },
  "test": {
    "JWT_SECRET": "randomSecretHere",
    "MONGODB_URI": "mongodb://testDatabaseUrlHere"
  }
}`
make a file called config.json in server/config/ folder and paste above code.
what happens is config.js loops through JSON file and assigns each key-value to a local node variable you access anyway in your program through `process.env.keyname`
the JWT Secret can be any random characters
and for the mongodbURI you can get a free 500mb online database here to test out https://mlab.com/

**Comment by hfahrudin** [comment]
Oh i just remember doing something similar to that. I hope you can explain it in your read me file to help anyone who want to clone your project. Thanks!

**Comment by Credwa** [comment]
Yeah will get to that later today :)
